[package]
name = "loadbalance" # Change the nmae of your wasm filter here
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
prost-build = "0.11.1"

[dependencies]
log = "0.4"
prost = "0.11.0"
proxy-wasm = "0.2.0"
rand = "0.7.0"
getrandom = { version = "0.2", features = ["js"] }
lazy_static = "1.4.0"